services:
    sql:
        image: sql-server
        container_name: sql
        build:
            dockerfile: build/SQL/Dockerfile
        ports:
            - "1433:1433"
        volumes:
            - sql-volume:/var/opt/mssql
    redis:
        image: redis-image
        container_name: "redis"
        build:
            dockerfile: build/Redis/Dockerfile
        ports:
            - "6379:6379"
    api:
        image: api-image
        container_name: api
        build:
            dockerfile: build/Api/Dockerfile
        environment:
            - SQL_HOST=sql
            - REDIS_HOST=redis
        ports:
            - 8000:80
        depends_on:
            - sql
            - redis
volumes:
    sql-volume:
        name: sql-volume